#!/usr/bin/Rscript

# This script converts DNA sequences downloaded from BOLD and retrieves the taxonomic identifier of the taxon from NCBI taxonomy,
# to create a new fasta file with the following information to be used with OBITools: taxid, scientific_name, and record id (from BOLD).
# It is necessary to have downloaded and extracted the NCBI taxdump (wget -m ftp://ftp.ncbi.nlm.nih.gov://pub/taxonomy/taxdump.tar.gz)# For those taxa whose rank is not included in NCBI taxonomy the script will look for the immediate parent in BOLD, and register the rank change.
# Author: Daniel Marquina

library(bold)
suppressMessages(library(CHNOSZ))
suppressMessages(library(seqinr))
library(optparse)

# Set file names for input and output files
options( warn = -1 )

option_list = list(
  make_option(c("-i", "--input_fasta"), type="character", default=NULL,
              help="fasta file with the sequences to be renamed", metavar="character"),
  make_option(c("-o", "--output_fasta"), type="character", default=NULL,
              help="Output file name [default = input file ending in _taxid.csv]", metavar="character"),
  make_option(c("-d", "--directory"), type="character", default=NULL,
              help="Directory where NCBI's taxdump is stored [default = current directory]", metavar="character")
)

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$input_fasta)){
  print_help(opt_parser)
  stop("At least one file must be provided: input fasta with the sequences to be renamed.", call.=FALSE)
}

if (is.null(opt$output_fasta)){
  opt$output_fasta <- paste(substr(opt$input_fasta,1,nchar(opt$input_fasta)-6),"_taxid.fasta",sep="")
}

if (is.null(opt$directory)){
  opt$directory <- getwd()
}

infile <- opt$input_fasta
outfile <- opt$output_fasta
directory <- opt$directory

# Import sequences
message("Reading reference fasta file from BOLD", "\r", appendLF = T)
seq_no_taxid <- read.fasta(infile, as.string = T, whole.header = T, forceDNAtolower=F)
message("> Imported ", length(seq_no_taxid), " sequences", "\r", appendLF = T)

# Import taxonomy info
message("Reading NCBI's taxonomy database", "\r", appendLF = T)
taxnames <- getnames(directory)
taxranks <- getnodes(directory)
message("> Taxonomy database ready", "\r", appendLF = T)

# Get taxids
boldid <- NULL
boldname <- NULL
taxid <- NULL
rank <- NULL
newname <- NULL
ori_name <- NULL
ori_rank <- NULL
message("Searching taxonomy database for taxids")
for (i in 1:length(seq_no_taxid)){
  message("Retrieving taxid for sequence ", i, " of ", length(seq_no_taxid), "\r", appendLF = T)
  boldid[i] <- gsub("\\|.*","", getName(seq_no_taxid[i]))
  boldname[i] <- strsplit(getName(seq_no_taxid), "\\|")[[i]][2]
  ori_name[i] <- boldname[i]
  if (length(grep("sp.", boldname[i]))!=0){
    boldname[i] <- strsplit(boldname[i], " ")[[1]][1]
  } else{}
  if (length(grep("cf.", boldname[i]))!=0){
    boldname[i] <- strsplit(boldname[i], " ")[[1]][1]
  } else{}
  if (length(grep("aff.", boldname[i]))!=0){
    boldname[i] <- strsplit(boldname[i], " ")[[1]][1]
  } else{}
  if (length(taxnames[taxnames$name==boldname[i],1])==0){
    ori_rank[i] <- bold_tax_name(boldname[i])$tax_rank
  } else{}
  while (length(taxnames[taxnames$name==boldname[i],1])==0){
    bold_tax <- bold_tax_name(boldname[i])
    parent_tax <- ifelse(length(bold_tax)!=1, bold_tax$parentname, strsplit(boldname[i], ' ')[[1]][1])
    message("!! Taxon *", boldname[i], "* not found in NCBI's taxonomy. Trying parent taxon", "\r", appendLF = T)
    boldname[i] <- parent_tax
    }
  taxid[i] <- taxnames$id[taxnames$name==boldname[i]]
  rank[i] <- as.character(taxranks$rank[taxranks$id==taxid[i]])
  message(">>> taxid registered for taxon *", boldname[i],"*\n", appendLF = T)
  if (ori_name[i]!=boldname[i]){
    newname[i] <- paste(boldid[i]," scientific_name=", boldname[i], "; taxid=",taxid[i],"; rank=",rank[i],"; original_db_name=", ori_name[i],"; original_db_rank=", ori_rank[i], ";", sep = "")
  } else{
    newname[i] <- paste(boldid[i]," scientific_name=", boldname[i], "; taxid=",taxid[i],"; rank=",rank[i],";", sep = "")
  }
}
for (i in 1:length(seq_no_taxid)){
  seq_no_taxid[[i]][1] <- gsub("-", "", getSequence(seq_no_taxid, as.string = T)[[i]])
}

# Write new fasta with obitools format
write.fasta(seq_no_taxid, newname, outfile, as.string = T, open = "w", nbchar = max(getLength(seq_no_taxid)))
message(outfile, " created with NCBI taxids")
