#!/usr/bin/env Rscript

# This script converts DNA sequences downloaded from BOLD and retrieves the taxonomic identifier of the taxon from NCBI taxonomy,
# to create a new fasta file with the following information to be used with OBITools: taxid, scientific_name, and record id (from BOLD).
# It can be run with an NCBI key to maximize up to 10 the number of queries per second to NCBI.

library(bold)
library(seqinr)
library(taxize)
library(optparse)

#Set file names for input and output files
options( warn = -1 )

option_list = list(
  make_option(c("-i", "--input_fasta"), type="character", default=NULL,
              help="fasta file with the sequences to be renamed", metavar="character"),
  make_option(c("-o", "--output_fasta"), type="character", default=NULL,
              help="Output file name [default = input file ending in _taxid.csv]", metavar="character"),
  make_option(c("-k", "--key_NCBI"), type="character", default=NULL,
              help="Output file name [default = input file ending in _taxid.csv]", metavar="character"),
  make_option(c("-t", "--taxon"), type="character", default=NULL,
              help="Taxonomic group of interest to resolve name duplications (optional)", metavar="character")
)

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$input_fasta)){
  print_help(opt_parser)
  stop("At least one file must be provided: input fasta with the sequences to be renamed.", call.=FALSE)
}

if (is.null(opt$output_fasta)){
  opt$output_fasta <- paste(substr(opt$input_fasta,1,nchar(opt$input_fasta)-6),"_taxid.fasta",sep="")
}

infile <- opt$input_fasta
outfile <- opt$output_fasta
key <- opt$key_NCBI
taxon <- opt$taxon

seq_no_taxid <- read.fasta(infile, as.string = T, whole.header = T, forceDNAtolower=F)

boldid <- NULL
boldname <- NULL
taxid <- NULL
rank <- NULL
newname <- NULL
for (i in 1:length(seq_no_taxid)){
  message("Retrieving taxid for sequence ", i, " of ", length(seq_no_taxid), "\r", appendLF = FALSE)
  boldid[i] <- gsub("\\|.*","", getName(seq_no_taxid[i]))
  boldname[i] <- bold_seq(ids=boldid[i])[[1]]$name
  if (length(grep("sp.", boldname[i]))!=0){
    boldname[i] <- strsplit(boldname[i], " ")[[1]][1]
  } else{}
  if (length(grep("cf.", boldname[i]))!=0){
    boldname[i] <- strsplit(boldname[i], " ")[[1]][1]
  } else{}
  if ("tax_rank" %in% colnames(bold_tax_name(boldname[i]))){
    rank[i] <- bold_tax_name(boldname[i])$tax_rank
    taxid[i] <- as.character(get_uid(boldname[i], rank_filter=rank[i], key= key, division_filter = taxon))[1]
  } else{
    rank[i] <- "unknown"
    taxid[i] <- "unknown"
  }
  newname[i] <- paste(boldid[i]," scientific_name=", boldname[i], "; taxid=",taxid[i],"; rank=",rank[i],";", sep = "")
}

for (i in 1:length(seq_no_taxid)){
  seq_no_taxid[[i]][1] <- gsub("-", "", getSequence(seq_no_taxid, as.string = T)[[i]])
}

write.fasta(seq_no_taxid, newname, outfile, as.string = T, open = "w", nbchar = max(getLength(seq_no_taxid)))
message(outfile, " created with NCBI taxids")
